name: ci-pipeline

on:
  push:
    branches:
      - tests

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:      
      matrix:        
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}      
      uses: actions/setup-node@v3      
      with:        
        node-version: ${{ matrix.node-version }}        

    - name: Install Dependencies
      run: |
        npm install

    - name: Run Tests
      run: |
        npm test

    # - name: Setup AWS CLI
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: eu-north-1  

    # - name: SSH and Pull Changes in EC2
    #   run: |
    #     # Install SSH client (might be already available in the runner)
    #     sudo apt-get install openssh-client

    #     # SSH into the EC2 instance and pull changes
    #     ssh -o StrictHostKeyChecking=no -i /path/to/your/private_key.pem ec2-user@13.49.67.132 "cd workspace/OrderApp/ && git pull"

    # - name: Build (if necessary)
    #   run: |
    #     # Build commands or Docker build for containerized apps.

    # - name: Deploy
    #   run: |
    #     # You can use AWS CLI, Azure CLI, etc., based on where you're deploying.
    #     # Ensure you've set up necessary secrets for deployments.

    # - name: Post-Deployment Checks
    #   run: |
    #     # Smoke tests or other post-deployment checks to ensure the deployed application is running.
